
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Thu Apr 22 11:11:36 EET 2010
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int MD = 7;
  public static final int MB = 5;
  public static final int EOF = 0;
  public static final int DB = 6;
  public static final int NM = 10;
  public static final int RB = 9;
  public static final int LB = 8;
  public static final int error = 1;
  public static final int PO = 3;
  public static final int MO = 4;
  public static final int SM = 2;
}

