
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Thu May 06 20:16:36 EEST 2010
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int LT = 5;
  public static final int ELSE = 19;
  public static final int CO = 12;
  public static final int IN = 22;
  public static final int IF = 21;
  public static final int GT = 6;
  public static final int ID = 26;
  public static final int CA = 13;
  public static final int AO = 3;
  public static final int FA = 2;
  public static final int LC = 16;
  public static final int LB = 14;
  public static final int RC = 17;
  public static final int RB = 15;
  public static final int MO = 9;
  public static final int PO = 8;
  public static final int FUNC = 20;
  public static final int EOF = 0;
  public static final int SM = 7;
  public static final int SL = 25;
  public static final int LETREC = 24;
  public static final int error = 1;
  public static final int LET = 23;
  public static final int DB = 11;
  public static final int EQ = 4;
  public static final int MB = 10;
  public static final int NM = 18;
  public static final int BF = 27;
}

